[{"line":3,"elements":[{"start_timestamp":"2024-11-24T09:55:26.567Z","before":[{"result":{"duration":1357251,"status":"passed"},"match":{"location":"com.digite.cloud.test.steps.AssignmentSteps.<init>(AssignmentSteps.java:34)"}}],"line":11,"name":"Create a post, verify it, comment on it, and verify the comment","description":"","id":"create--verify-and-comment-on-discussion-post;create-a-post--verify-it--comment-on-it--and-verify-the-comment;;2","type":"scenario","keyword":"Scenario Outline","steps":[{"result":{"error_message":"org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//ul/li[@id='homeIcon']/a\"}\n  (Session info: chrome=131.0.6778.85)\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nBuild info: version: '4.11.0', revision: '040bc5406b'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-1019-aws', java.version: '22.0.2'\nDriver info: org.openqa.selenium.chrome.ChromeDriver\nCommand: [f03dcf3499f71cbf7ebfdfc181e77908, findElement {using=xpath, value=//ul/li[@id='homeIcon']/a}]\nCapabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.85, chrome: {chromedriverVersion: 131.0.6778.85 (3d81e41b6f3a..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45647}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:45647/devtoo..., se:cdpVersion: 131.0.6778.85, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}\nSession ID: f03dcf3499f71cbf7ebfdfc181e77908\n\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)\n\tat org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)\n\tat org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)\n\tat org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)\n\tat org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)\n\tat com.digite.actions.commands.Common.elementClick(Common.java:115)\n\tat com.digite.lp.businesslogic.Assignment.logini(Assignment.java:47)\n\tat com.digite.cloud.test.steps.AssignmentSteps.lambda$new$1(AssignmentSteps.java:42)\n\tat âœ½.user logs in with email \"test.apr221@digite.com\" and password \"welcome@1\"(file:///home/utkarsh_singh/Music/parallel_testing/src/test/resources/features/assignment.feature:7)\n","duration":24840359766,"status":"failed"},"line":7,"name":"user logs in with email \"test.apr221@digite.com\" and password \"welcome@1\"","match":{"arguments":[{"val":"\"test.apr221@digite.com\"","offset":24},{"val":"\"welcome@1\"","offset":62}],"location":"com.digite.cloud.test.steps.AssignmentSteps.<init>(AssignmentSteps.java:38)"},"keyword":"Given "}],"tags":[{"name":"@Sanity"},{"name":"@Critical"},{"name":"@ki"}]}],"name":"Create, Verify and Comment on Discussion Post","description":"","id":"create--verify-and-comment-on-discussion-post","keyword":"Feature","uri":"file:src/test/resources/features/assignment.feature","tags":[]},{"line":1,"elements":[{"start_timestamp":"2024-11-24T09:55:51.430Z","line":2,"name":"Failure while executing Cucumber","description":"","id":"failure;failure-while-executing-cucumber","type":"scenario","keyword":"Scenario","steps":[{"result":{"duration":0,"status":"passed"},"line":3,"name":"Cucumber failed while executing","match":{"arguments":[],"location":"io.cucumber.core.Failure.failure_while_executing_cucumber()"},"keyword":"When "},{"result":{"duration":0,"error_message":"io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.\n\tat io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)\n\tat io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)\n\tat io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:97)\n\tat io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:145)\n\tat io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:57)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\n\tat java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java)\n\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\n\tat java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:151)\n\tat org.testng.internal.thread.graph.TestNGFutureTask.<init>(TestNGFutureTask.java:15)\n\tat org.testng.internal.thread.graph.GraphOrchestrator.runNodes(GraphOrchestrator.java:55)\n\tat org.testng.internal.thread.graph.GraphOrchestrator.run(GraphOrchestrator.java:43)\n\tat org.testng.TestTaskExecutor.execute(TestTaskExecutor.java:87)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:800)\n\tat org.testng.TestRunner.run(TestRunner.java:619)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\n\tat org.testng.TestNG.run(TestNG.java:1101)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n\tSuppressed: io.cucumber.core.backend.CucumberBackendException\n\t\tat io.cucumber.spring.TestContextAdaptor.notifyTestContextManagerAboutBeforeTestMethod(TestContextAdaptor.java:58)\n\t\tat io.cucumber.spring.TestContextAdaptor.start(TestContextAdaptor.java:48)\n\t\tat io.cucumber.spring.SpringFactory.start(SpringFactory.java:153)\n\t\tat io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:134)\n\t\tat io.cucumber.core.runner.Runner.runPickle(Runner.java:70)\n\t\tat io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)\n\t\tat io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)\n\t\tat io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)\n\t\tat io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)\n\t\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\t\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\t\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\n\t\tat org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)\n\t\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.<init>(CompletableFuture.java:1754)\n\t\tat java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)\n\t\tat java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)\n\t\tat org.testng.internal.invokers.MethodRunner.runInParallel(MethodRunner.java:143)\n\t\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:950)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\n\t\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\t\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\t\t... 23 more\n\tCaused by: java.util.ConcurrentModificationException\n\t\tat java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)\n\t\tat com.digite.actions.drivercapabilities.CucumberBrowserScope.get(CucumberBrowserScope.java:16)\n\t\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371)\n\t\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1273)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1234)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)\n\t\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)\n\t\tat io.cucumber.spring.TestContextAdaptor.notifyTestContextManagerAboutBeforeTestMethod(TestContextAdaptor.java:54)\n\t\t... 50 more\n\tSuppressed: io.cucumber.core.backend.CucumberBackendException\n\t\tat io.cucumber.spring.TestContextAdaptor.notifyTestContextManagerAboutBeforeTestMethod(TestContextAdaptor.java:58)\n\t\tat io.cucumber.spring.TestContextAdaptor.start(TestContextAdaptor.java:48)\n\t\tat io.cucumber.spring.SpringFactory.start(SpringFactory.java:153)\n\t\tat io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:134)\n\t\tat io.cucumber.core.runner.Runner.runPickle(Runner.java:70)\n\t\tat io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:129)\n\t\tat io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)\n\t\tat io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:129)\n\t\tat io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)\n\t\tat io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)\n\t\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\t\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\t\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\n\t\tat org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)\n\t\tat --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)\n\t\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.<init>(CompletableFuture.java:1754)\n\t\tat java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)\n\t\tat java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)\n\t\tat org.testng.internal.invokers.MethodRunner.runInParallel(MethodRunner.java:143)\n\t\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:950)\n\t\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\n\t\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\t\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\t\t... 23 more\n\tCaused by: java.util.ConcurrentModificationException\n\t\tat java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)\n\t\tat com.digite.actions.drivercapabilities.CucumberBrowserScope.get(CucumberBrowserScope.java:16)\n\t\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371)\n\t\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1273)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1234)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)\n\t\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)\n\t\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)\n\t\tat io.cucumber.spring.TestContextAdaptor.notifyTestContextManagerAboutBeforeTestMethod(TestContextAdaptor.java:54)\n\t\t... 50 more\n","status":"failed"},"line":4,"name":"Cucumber will report this error:","match":{"arguments":[],"location":"io.cucumber.core.Failure.cucumber_reports_this_error()"},"keyword":"Then "}]}],"name":"Test run failed","description":"There were errors during the execution","id":"failure","keyword":"Feature","uri":"classpath:io/cucumber/core/failure.feature","tags":[]}]